CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "Channels" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ChannelId" text NULL,
    "Title" text NULL,
    "Description" text NULL,
    "PublishedAt" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Channels" PRIMARY KEY ("Id")
);

CREATE TABLE "Videos" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "VideoId" text NULL,
    "Title" text NULL,
    "Description" text NULL,
    "PublishedAt" timestamp without time zone NOT NULL,
    "ChannelId" text NULL,
    CONSTRAINT "PK_Videos" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20210617180207_Initial', '5.0.7');

COMMIT;

